### ISSUE TITLE
Use semver tags for go modules

### ISSUE THREAD

**Issue by cugu** [Velocidex/go-ntfs#11]
e.g. `v0.2.0`, the current `v0.1` does not seem to work

**Comment by scudette** [comment]
I am not sure we are ready for a stable API yet: https://semver.org/:

Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

When you say it does not seem to work do you mean there are bugs in parsing of NTFS? We probably will not support 0.1 because the code has been heavily refactored now (and is currently in use in Velociraptor so it would be good if you can find some bugs).

**Comment by cugu** [comment]
I am not saying that you should have a stable API by now. Just use e.g. `v0.1.0` instead of `v0.1` for tags. 

I'll report any bug I find, but it so far it works quite well. (As soon as I figured out the NewPagedReader stuff.)

**Comment by cugu** [comment]
https://github.com/Velocidex/go-ntfs/releases/tag/v0.1.1 is seen as a valid go mod version now.
