### ISSUE TITLE
Request for Example: Directly Reading and Parsing Filenames from $MFT File without Copying

### ISSUE THREAD

**Issue by hkhk368** [Velocidex/go-ntfs#85]
@scudette 
Thank you for sharing the code of this library. As a newbie to MFT, could you write an example? I would greatly appreciate it if you could read the $MFT file directly without copying it, and then parse out the file name, file size, modified time of each file.

**Comment by scudette** [comment]
See the example code here https://github.com/Velocidex/go-ntfs/blob/33eadbbaf1f20b4d578b59e2d19279088cc71993/bin/mft.go#L48 

This program has all the options to demonstrate how to use the library to list files, read streams etc. The other files in this directory contain many more example functions.

**Comment by scudette** [comment]
You can dump $MFT directly using the `ntfs.exe cat` command but this is not as good as opening it from the image directly because it makes it impossible to string together the full path by walking the mft entries in reverse.

We mostly use this library inside Velociraptor so you can also look at that code:
https://github.com/Velocidex/velociraptor/blob/f143b88ee50f5cf14ff55a4916e24143fe61b8a6/vql/parsers/ntfs.go

I added support to the mft code to be able to open the live drive instead of from an image in #86 so you can now just run directly on \\.\c:

![image](https://github.com/Velocidex/go-ntfs/assets/3856546/f254a4a9-50b4-4d10-a644-b4f7727987b6)
